### ISSUE TITLE
Wrong FaceAuthenticationStatus

### ISSUE THREAD

**Issue by yamaha252** [idenfy/FlutterSDK#10]
Wrong status received after closing the face authentication widget manually before finishing the process.

**AR:** FaceAuthenticationStatus.FAILED
**ER:** FaceAuthenticationStatus.EXIT

idenfy_sdk_flutter: ^2.0.2

**Comment by viktasidenfy** [comment]
Did it happen only once? If the SDK wasn't able to close properly, FAILED status will be returned.

**Comment by yamaha252** [comment]
It happens every time I close the widget by a button on the top left corner (confirmed exit in the dialog) or by a native back action

**Comment by viktasidenfy** [comment]
Could you specify the SDK version and the device you are using?

**Comment by yamaha252** [comment]
idenfy_sdk_flutter 2.0.2
Flutter 3.3.9
Dart 2.18.5

Tested on Android 13 (Google Pixel 6 Pro)

**Comment by viktasidenfy** [comment]
Can you replicate this issue on our sample project in this repo? We were not able to replicate it. 
Also, could you provide us (support@idenfy.com) some of the scan-ref's of the verifications this issue occurred on. We will check the logs. Thank you!

**Comment by yamaha252** [comment]
Reproduced it in the sample app. 
The ScanRef I used 9c782c7b-718b-11ed-9b8f-066802deb4c7

https://photos.app.goo.gl/YiuTLq7bfmp1j6PX8

**Comment by viktasidenfy** [comment]
As we can see from the logs, the identification was not successfully finished. That is why there was a problem closing the Face Authentication SDK successfully. We have released version 2.0.6. Now the EXIT status will always return, even if the SDK could not close properly. 
Furthermore, please make sure `/identification/facial-auth/$scanref/check-status/` and `/partner/authentication-info` endpoints returned a successful status, before launching the SDK (same as in our example code).
