### ISSUE TITLE
App store rejection because of NFC feature

### ISSUE THREAD

**Issue by akifarhan** [idenfy/FlutterSDK#13]
### What was the expected behaviour?
We tried to submit a new app to the store using iDenfy SDK 1.7.0 and got rejected because of an NFC feature that we are not using and I believe it's coming from this SDK.

### What happened instead
The app has been rejected for NFC usage and we need to provide proof and demo for the NFC feature. 

<img width="1236" alt="image" src="https://github.com/idenfy/FlutterSDK/assets/38977468/2bd53862-f907-4f47-a899-391076cd81ca">

Please suggest how to mitigate this issue. Do you have any video that we can use to show the functionality to AppStore or is there any way we could use the feature to screen record the functionality using our app? Or can I disabled the unused NFC feature for my app?

**Comment by 1mavic** [comment]
@akifarhan hi!
In documentation for ios sdk there is caution banner, with this case.
https://documentation.idenfy.com/mobile/iOS/ios-sdk

During the review process of your app, Apple might ask you to describe NFC usage in your app, even if you don't have [NFC feature](https://documentation.idenfy.com/mobile/iOS/ios-sdk#nfc-support) enabled. To successfully pass the verification, try to send them this [video](https://s3.eu-west-1.amazonaws.com/sdk.builds/ios-tutorials/idenfy_nfc_for_apple_store.mp4), which shows NFC usage in the KYC flow. If Apple still does not confirm, contact us for further communication.

**Comment by akifarhan** [comment]
Hi, @1mavic ! Thank you for getting back to me. I already submitted the video and got it approved. Is there any plan to port out the NFC feature to separate SDK since we don't have the NFC feature enabled?
