### ISSUE TITLE
Error installing iDenfySDK

### ISSUE THREAD

**Issue by 1mavic** [idenfy/FlutterSDK#17]
Hello!

I'm currently using idenfy_sdk_flutter version 2.3.6, but I've started encountering an error when running `pod install`.

Here’s the error message:

> [!] Error installing iDenfySDK
[!] /usr/bin/curl -f -L -o /var/folders/8d/6x79x89x52z_h9prv_ssw7s80000gn/T/d20241112-33097-2admgr/file.zip https://s3-eu-west-1.amazonaws.com/sdk.builds/ios-sdk/8.2.1/iDenfySDKxcf.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.14.3 cocoapods-downloader/2.1'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403

It seems that the requested URL is returning a 403 error. Could you please advise on how to resolve this?

**Comment by viktasidenfy** [comment]
Please use version 2.5.4 of iDenfy Flutter SDK (version 8.5.0 of ios build) and above.

**Comment by 1mavic** [comment]
@viktasidenfy
Upgrading to a newer version isn’t an option, as it would require increasing the minSdkVersion to 24, which we’d like to avoid.

**Comment by viktasidenfy** [comment]
I have restored 8.2.1 version, you can try again.
P.S. If you are not using Face authentication feature, you can upgrade the SDK package to latest version and override the minSDK version in AndroidManifest. The identity verification flow should work fine.

**Comment by 1mavic** [comment]
Thank you.
We will try!
