### ISSUE TITLE
Problems when deploying to iOS

### ISSUE THREAD

**Issue by ivangalkindeveloper** [idenfy/FlutterSDK#2]
Greetings
After installing the iDenfy SDK, unfortunately, Ios gives the following error
Is it possible to somehow solve this?

idenfy_sdk_flutter-1.2.0
cannot find 'IdenfyBuilderV2' in scope 
   let idenfySettingsV2 = IdenfyBuilderV2()
cannot find 'IdenfyController' in scope 
   let idenfyController = IdenfyController.shared

![Снимок экрана 2021-10-15 в 17 10 05](https://user-images.githubusercontent.com/78663629/137555959-9211951c-c449-4cca-b02e-426cf0f75e1f.png)

[✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-x64, locale
    ru-RU)
    • Flutter version 2.5.2 at /Users/ivangalkin/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (2 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/ivangalkin/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.61.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • iPhone 12 (mobile) • 8CCBC4FA-EA67-474B-95CD-03765CEB6B9D • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 94.0.4606.81

**Comment by viktor-idenfy** [comment]
Hello, the issue is solved in the 1.4.0 version. Please check it
