### ISSUE TITLE
Failed to build module; this SDK is not supported by the compiler

### ISSUE THREAD

**Issue by akifarhan** [idenfy/FlutterSDK#4]
Hi, when trying to build for iOS I've received this error from Xcode. 

I already followed the steps for [Troubleshooting compile errors](https://pub.dev/packages/idenfy_sdk_flutter#5-troubleshooting-compile-errors) except for the _Use different Subspec_ part which I'm not sure how can it be done. 

Any ideas on how it can be solved?

```
Command CompileSwiftSources failed with a nonzero exit code
    ld: warning: dylib (/Users/akifarhan/development/spectre/build/ios/Release-dev-iphoneos/MDFInternationalization/MDFInternationalization.framework/MDFInternationalization) was built for newer iOS version
    (11.0) than being linked (10.0)
    ld: warning: ignoring file /Users/akifarhan/development/spectre/build/ios/Release-dev-iphoneos/MDFInternationalization/MDFInternationalization.framework/MDFInternationalization, building for iOS-armv7 but
    attempting to link with file built for iOS-arm64
    remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
    /Users/akifarhan/development/spectre/build/ios/Release-dev-iphoneos/XCFrameworkIntermediates/iDenfySDK/iDenfyLiveness/idenfyviews.framework/Modules/idenfyviews.swiftmodule/armv7-apple-ios.swiftinterface:7
    :8: error: could not find module 'Lottie' for target 'armv7-apple-ios'; found: arm64, arm64-apple-ios, at:
    /Users/akifarhan/development/spectre/build/ios/Release-dev-iphoneos/lottie-ios/Lottie.framework/Modules/Lottie.swiftmodule
    import Lottie
           ^
    /Users/akifarhan/development/spectre/build/ios/Release-dev-iphoneos/XCFrameworkIntermediates/iDenfySDK/iDenfyLiveness/IdenfyLiveness.framework/Modules/IdenfyLiveness.swiftmodule/armv7-apple-ios.swiftinter
    face:10:8: error: failed to build module 'idenfyviews'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)', while this
    compiler is 'Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)'). Please select a toolchain which matches the SDK.
    import idenfyviews
           ^
    /Users/akifarhan/development/spectre/build/ios/Release-dev-iphoneos/XCFrameworkIntermediates/iDenfySDK/iDenfyLiveness/iDenfySDK.framework/Modules/iDenfySDK.swiftmodule/armv7-apple-ios.swiftinterface:10:8:
    error: failed to build module 'IdenfyLiveness'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)', while this compiler
    is 'Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)'). Please select a toolchain which matches the SDK.
    import IdenfyLiveness
           ^
    /Users/akifarhan/development/spectre/build/ios/Release-dev-iphoneos/XCFrameworkIntermediates/iDenfySDK/iDenfyLiveness/idenfyNFCReading.framework/Modules/idenfyNFCReading.swiftmodule/armv7-apple-ios.swifti
    nterface:6:8: error: no such module 'CryptoKit'
    import CryptoKit
           ^
    /Users/akifarhan/development/spectre/build/ios/Release-dev-iphoneos/XCFrameworkIntermediates/iDenfySDK/iDenfyLiveness/idenfyviews.framework/Modules/idenfyviews.swiftmodule/armv7-apple-ios.swiftinterface:7
    :8: error: could not find module 'Lottie' for target 'armv7-apple-ios'; found: arm64, arm64-apple-ios, at:
    /Users/akifarhan/development/spectre/build/ios/Release-dev-iphoneos/lottie-ios/Lottie.framework/Modules/Lottie.swiftmodule
    import Lottie
           ^
    /Users/akifarhan/development/flutter/.pub-cache/hosted/pub.dartlang.org/idenfy_sdk_flutter-1.4.0/ios/Classes/SwiftIdenfySdkFlutterPlugin.swift:3:8: error: failed to build module 'iDenfySDK'; this SDK is
    not supported by the compiler (the SDK is built with 'Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)', while this compiler is 'Apple Swift version 5.5.2 (swiftlang-1300.0.47.5
    clang-1300.0.29.30)'). Please select a toolchain which matches the SDK.
    import iDenfySDK
           ^
```

<details>
<summary>flutter doctor</summary>
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale en-GB)
    • Flutter version 2.8.1 at /Users/akifarhan/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 months ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/akifarhan/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = /Users/akifarhan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.66.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • iPhone 13 Pro Max (mobile) • DC511D99-A060-4078-B72C-2B7F52DD9DFD • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 99.0.4844.51

• No issues found!
</details>

**Comment by viktor-idenfy** [comment]
You need to add use_frameworks! line in your Podfile. We will update the documentation to make it easier, but you can check a sample Podfile for now:
[https://github.com/idenfy/FlutterSDK/blob/main/example/ios/Podfile](https://github.com/idenfy/FlutterSDK/blob/main/example/ios/Podfile)

**Comment by akifarhan** [comment]
I've already added `use_frameworks!` before in my Podfile, but it still did not work.

However, after checking the sample Podfile, I found that I missed this part that was not included in the documentation.

```
if target.name == "idenfy_sdk_flutter"
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
```

After adding this part to the Podfile, I was able to build my app.
