### ISSUE TITLE
Unable to run on iOS 12.5.5

### ISSUE THREAD

**Issue by akifarhan** [idenfy/FlutterSDK#5]
Hi, I've faced some issue with this sdk which it can't run on certain iPhone models such as device running on iOS 12.5.5. From the output in the debug console it seems like my app managed to be built by Xcode but cannot run when finish installed. 

When I tried to build from Xcode, I received this output:
```
Library not loaded: /System/Library/Frameworks/CryptoTokenKit.framework/CryptoTokenKit Referenced from: /private/var/containers/Bundle/Application/CFC2CCA2-E2DD-442F-9E20-DF0A9BBA7281/Runner.app/Frameworks/idenfyNFCReading.framework/idenfyNFCReading Reason: image not found
```

**Comment by akifarhan** [comment]
Any update on this?

**Comment by Asadeck** [comment]
@akifarhan got any solution?

**Comment by akifarhan** [comment]
@Asadeck I've tried upgrading the package to `1.7.0` and it works. No crash. But I'm not really sure what's the issue. What version are you using right now?

**Comment by Asadeck** [comment]
idenfy_sdk_flutter: ^1.7.1

**Comment by Asadeck** [comment]
@akifarhan Thanks for help, i think there is some issue with my local machine, i tried it on another and the SDK is working perfectly for iOS.

**Comment by viktor-idenfy** [comment]
Thanks, @Asadeck for the help! Glad to see such collaboration :) If any help is still needed, feel free to open an issue.

**Comment by viktor-idenfy** [comment]
Thanks, @Asadeck for the help! Glad to see such collaboration :) If any help is still needed, feel free to open an issue.
