### ISSUE TITLE
Unable to check in Android

### ISSUE THREAD

**Issue by groomkrunal** [idenfy/FlutterSDK#8]
When I try to run app in android i got this error "It say Custom Views are not allowed."

**Comment by viktasidenfy** [comment]
Your plan does not include full customisation of the SDK. If you wish to enable it, please contact support@idenfy.com for more information.

Or if your want to disable customisation, comment out the following line in the Application.kt file:

`IdenfyController.getInstance().idenfyComposableViews = idenfyComposeViews`
