### ISSUE TITLE
Failed to build module; this SDK is not supported by the compiler

### ISSUE THREAD

**Issue by Asadeck** [idenfy/FlutterSDK#9]
Swift Compiler Error (Xcode): No type named 'AnimationView' in module 'Lottie'
/Users/asads-laptop.local/Desktop/frontend/wallet/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/iDenfySDK/iDenfyLiveness/idenfyviews.framework/Modules/idenfyviews.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:155:35

Swift Compiler Error (Xcode): No type named 'AnimationView' in module 'Lottie'
/Users/asads-laptop.local/Desktop/frontend/wallet/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/iDenfySDK/iDenfyLiveness/idenfyviews.framework/Modules/idenfyviews.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:184:74

Swift Compiler Error (Xcode): No type named 'AnimationView' in module 'Lottie'
/Users/asads-laptop.local/Desktop/frontend/wallet/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/iDenfySDK/iDenfyLiveness/idenfyviews.framework/Modules/idenfyviews.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:421:75

Swift Compiler Error (Xcode): No type named 'AnimationView' in module 'Lottie'
/Users/asads-laptop.local/Desktop/frontend/wallet/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/iDenfySDK/iDenfyLiveness/idenfyviews.framework/Modules/idenfyviews.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:446:114

Swift Compiler Error (Xcode): No type named 'AnimationView' in module 'Lottie'
/Users/asads-laptop.local/Desktop/frontend/wallet/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/iDenfySDK/iDenfyLiveness/idenfyviews.framework/Modules/idenfyviews.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:532:74

Swift Compiler Error (Xcode): No type named 'AnimationView' in module 'Lottie'
/Users/asads-laptop.local/Desktop/frontend/wallet/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/iDenfySDK/iDenfyLiveness/idenfyviews.framework/Modules/idenfyviews.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:684:29

Swift Compiler Error (Xcode): No type named 'AnimationView' in module 'Lottie'
/Users/asads-laptop.local/Desktop/frontend/wallet/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/iDenfySDK/iDenfyLiveness/idenfyviews.framework/Modules/idenfyviews.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:690:68

Swift Compiler Error (Xcode): No type named 'AnimationView' in module 'Lottie'
/Users/asads-laptop.local/Desktop/frontend/wallet/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/iDenfySDK/iDenfyLiveness/idenfyviews.framework/Modules/idenfyviews.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:796:68

Swift Compiler Error (Xcode): No type named 'AnimationView' in module 'Lottie'
/Users/asads-laptop.local/Desktop/frontend/wallet/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/iDenfySDK/iDenfyLiveness/idenfyviews.framework/Modules/idenfyviews.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:1518:45

Swift Compiler Error (Xcode): No type named 'AnimationView' in module 'Lottie'
/Users/asads-laptop.local/Desktop/frontend/wallet/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/iDenfySDK/iDenfyLiveness/idenfyviews.framework/Modules/idenfyviews.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:1527:84

Swift Compiler Error (Xcode): No type named 'AnimationView' in module 'Lottie'
/Users/asads-laptop.local/Desktop/frontend/wallet/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/iDenfySDK/iDenfyLiveness/idenfyviews.framework/Modules/idenfyviews.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:1626:36

Swift Compiler Error (Xcode): No type named 'AnimationView' in module 'Lottie'
/Users/asads-laptop.local/Desktop/frontend/wallet/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/iDenfySDK/iDenfyLiveness/idenfyviews.framework/Modules/idenfyviews.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:1640:75

Swift Compiler Error (Xcode): No type named 'AnimationView' in module 'Lottie'
/Users/asads-laptop.local/Desktop/frontend/wallet/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/iDenfySDK/iDenfyLiveness/idenfyviews.framework/Modules/idenfyviews.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:1669:36

Swift Compiler Error (Xcode): No type named 'AnimationView' in module 'Lottie'
/Users/asads-laptop.local/Desktop/frontend/wallet/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/iDenfySDK/iDenfyLiveness/idenfyviews.framework/Modules/idenfyviews.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:1683:75

Swift Compiler Error (Xcode): No type named 'AnimationView' in module 'Lottie'
/Users/asads-laptop.local/Desktop/frontend/wallet/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/iDenfySDK/iDenfyLiveness/idenfyviews.framework/Modules/idenfyviews.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:1703:36

Swift Compiler Error (Xcode): No type named 'AnimationView' in module 'Lottie'
/Users/asads-laptop.local/Desktop/frontend/wallet/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/iDenfySDK/iDenfyLiveness/idenfyviews.framework/Modules/idenfyviews.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:1716:75

Swift Compiler Error (Xcode): No type named 'AnimationView' in module 'Lottie'
/Users/asads-laptop.local/Desktop/frontend/wallet/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/iDenfySDK/iDenfyLiveness/idenfyviews.framework/Modules/idenfyviews.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:1838:36

Swift Compiler Error (Xcode): No type named 'AnimationView' in module 'Lottie'
/Users/asads-laptop.local/Desktop/frontend/wallet/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/iDenfySDK/iDenfyLiveness/idenfyviews.framework/Modules/idenfyviews.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:1852:75

Swift Compiler Error (Xcode): No type named 'AnimationView' in module 'Lottie'
/Users/asads-laptop.local/Desktop/frontend/wallet/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/iDenfySDK/iDenfyLiveness/idenfyviews.framework/Modules/idenfyviews.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:1935:29

Swift Compiler Error (Xcode): No type named 'AnimationView' in module 'Lottie'
/Users/asads-laptop.local/Desktop/frontend/wallet/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/iDenfySDK/iDenfyLiveness/idenfyviews.framework/Modules/idenfyviews.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:1941:68

Swift Compiler Error (Xcode): No type named 'AnimationView' in module 'Lottie'
/Users/asads-laptop.local/Desktop/frontend/wallet/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/iDenfySDK/iDenfyLiveness/idenfyviews.framework/Modules/idenfyviews.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:1962:36

Swift Compiler Error (Xcode): No type named 'AnimationView' in module 'Lottie'
/Users/asads-laptop.local/Desktop/frontend/wallet/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/iDenfySDK/iDenfyLiveness/idenfyviews.framework/Modules/idenfyviews.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:1980:75

Swift Compiler Error (Xcode): No type named 'AnimationView' in module 'Lottie'
/Users/asads-laptop.local/Desktop/frontend/wallet/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/iDenfySDK/iDenfyLiveness/idenfyviews.framework/Modules/idenfyviews.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:2002:35

Swift Compiler Error (Xcode): No type named 'AnimationView' in module 'Lottie'
/Users/asads-laptop.local/Desktop/frontend/wallet/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/iDenfySDK/iDenfyLiveness/idenfyviews.framework/Modules/idenfyviews.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:2031:74

Swift Compiler Error (Xcode): Failed to build module 'idenfyviews'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)', while this compiler is 'Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)'). Please select a toolchain which matches the SDK.
/Users/asads-laptop.local/Desktop/frontend/wallet/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/iDenfySDK/iDenfyLiveness/IdenfyLiveness.framework/Modules/IdenfyLiveness.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:10:7

Swift Compiler Error (Xcode): Failed to build module 'IdenfyLiveness'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)', while this compiler is 'Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)'). Please select a toolchain which matches the SDK.
/Users/asads-laptop.local/Desktop/frontend/wallet/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/iDenfySDK/iDenfyLiveness/iDenfySDK.framework/Modules/iDenfySDK.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:10:7

Swift Compiler Error (Xcode): Failed to build module 'iDenfySDK'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)', while this compiler is 'Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)'). Please select a toolchain which matches the SDK.
/Users/asads-laptop.local/flutter/.pub-cache/hosted/pub.dartlang.org/idenfy_sdk_flutter-1.7.1/ios/Classes/SwiftIdenfySdkFlutterPlugin.swift:2:7

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro Max.

**Comment by Asadeck** [comment]
i have followed the steps from: https://github.com/idenfy/FlutterSDK/issues/4. but nothing is working.

**Comment by viktasidenfy** [comment]
Resolving this issue through support@idenfy.com.
